### ISSUE TITLE
HQ приходится включать при каждом запуске

### ISSUE THREAD

**Issue by vvrnv** [debug45/Yandex-Music#9]
а можно сделать так, чтобы HQ всегда было включено, если я включил один раз? а то приходится при каждом запуске включать. на мобилке у них всегда включено

**Comment by debug45** [comment]
К сожалению, не получится. Это чисто внутренняя кухня самого сайта, лишь открываемого внутри приложения.

**Comment by vvrnv** [comment]
эх, жаль.
